#!/bin/bash
#
# Copyright (c) 2020-present, Adriano Lange.  All rights reserved.
# This source code is licensed under both the GPLv2 (found in the
# LICENSE.GPLv2 file in the root directory) and Apache 2.0 License
# (found in the LICENSE.Apache file in the root directory).
#
# Program used to select the applications within the AppImage

function usage() {
	echo "	Usage:"
	echo "		main   <rocksdb_test params>"
	echo "		helper <rocksdb_test_helper params>"
}

function main() {
	if [ "$1" == '--test' ]; then
		shift 1
	elif [ -z `$APPDIR/bin/which docker` ]; then
		echo "ERROR: docker not found"
		exit 1
	fi
	
	case "$1" in
		main)
			shift 1
			rocksdb_test "$@"
		;;
		helper)
			shift 1
			rocksdb_test_helper.py "$@"
		;;
		'--help')
			usage
		;;
		'-h')
			usage
		;;
		*)
			usage
			exit 1
		;;
	esac
	exit 0
}

function getcpid() {
	cpids=$(pgrep -P $1|xargs)
	for cpid in $cpids; do
		echo "$cpid"
		getcpid $cpid
	done
}

function handler() {
	for i in $(getcpid $$); do
		echo "kill child process $i"
		kill -s "$1" "$i"
	done
	exit 1
}

trap 'handler SIGINT' INT
trap 'handler SIGTERM' TERM
main "$@"
